 # config/meta.yml
 meta_product_name: "Satellites above me"
 meta_title: "Satellites above me - Take a look at the satellites above you"
 meta_description: "Track satellites flying above the users' locattion"
 meta_image: "star-bg.png" # should exist in `app/assets/images/`