 # config/meta.yml
 meta_product_name: "Satellites above me"
 meta_title: "Satellites above me - Easy Satellite Tracking"
 meta_description: "Track and search Starlink, Athlas, Thorad, ISS satellites longitude and latitude in real time."
 meta_image: "star-bg.png" # should exist in `app/assets/images/`